vich_uploader:
  db_driver: orm

  mappings:
    products:
      uri_prefix: /images/patentes
      upload_destination: '%kernel.project_dir%/public/uploads/images/patentes'
      namer:              vich_uploader.namer_uniqid
